
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author usrlab25
 */
public class JFrame_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
        threadBotao = new Thread();
        threadBotao2 = new Thread();
        listaCauda = new ArrayList<JButton>();
        listaCauda2 = new ArrayList<JButton>();
        placar1.setFocusable(false);
        placar2.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal = new javax.swing.JPanel();
        jButton_cobrinha = new javax.swing.JButton();
        jButton_fruta = new javax.swing.JButton();
        jButton_cobrinha2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        placar2 = new javax.swing.JTextField();
        placar1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_cobrinha.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton_cobrinha.setText("1");
        jButton_cobrinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cobrinhaActionPerformed(evt);
            }
        });
        jButton_cobrinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_cobrinhaKeyPressed(evt);
            }
        });

        jButton_fruta.setBackground(new java.awt.Color(204, 255, 0));
        jButton_fruta.setText("#");

        jButton_cobrinha2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton_cobrinha2.setText("2");
        jButton_cobrinha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cobrinha2ActionPerformed(evt);
            }
        });
        jButton_cobrinha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_cobrinha2KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PLACAR:");

        jLabel2.setText("x");

        placar2.setEditable(false);

        placar1.setEditable(false);

        jLabel3.setText("Jogad.1");

        jLabel4.setText("Jogad.2");

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_fruta)
                .addGap(239, 239, 239))
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_cobrinha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_cobrinha2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3)))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(placar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addComponent(jButton_cobrinha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton_fruta)
                .addGap(56, 56, 56)
                .addComponent(jButton_cobrinha2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cobrinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cobrinhaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_cobrinhaActionPerformed

    private void jButton_cobrinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_cobrinhaKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                if (threadBotao2.isAlive()) {
                    threadBotao2.suspend();
                }
                threadBotao2 = new Thread() {
                    public void run() {
                        paraCima1();
                    }
                };
                threadBotao2.start();
                break;

            case KeyEvent.VK_DOWN:
                if (threadBotao2.isAlive()) {
                    threadBotao2.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao2 = new Thread() {
                    public void run() {
                        paraBaixo1();
                    }
                };
                threadBotao2.start();
                break;

            case KeyEvent.VK_LEFT:
                if (threadBotao2.isAlive()) {
                    threadBotao2.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao2 = new Thread() {
                    public void run() {
                        paraEsquerda1();
                    }
                };
                threadBotao2.start();
                break;

            case KeyEvent.VK_RIGHT:
                if (threadBotao2.isAlive()) {
                    threadBotao2.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao2 = new Thread() {
                    public void run() {
                        paraDireita1();
                    }
                };
                threadBotao2.start();
                break;
        }
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_W:
                if (threadBotao.isAlive()) {
                    threadBotao.suspend();
                }
                threadBotao = new Thread() {
                    public void run() {
                        paraCima();
                    }
                };
                threadBotao.start();
                break;

            case KeyEvent.VK_S:
                if (threadBotao.isAlive()) {
                    threadBotao.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao = new Thread() {
                    public void run() {
                        paraBaixo();
                    }
                };
                threadBotao.start();
                break;

            case KeyEvent.VK_A:
                if (threadBotao.isAlive()) {
                    threadBotao.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao = new Thread() {
                    public void run() {
                        paraEsquerda();
                    }
                };
                threadBotao.start();
                break;

            case KeyEvent.VK_D:
                if (threadBotao.isAlive()) {
                    threadBotao.suspend();
                    //System.out.println("suspendendo a thread");
                }
                threadBotao = new Thread() {
                    public void run() {
                        paraDireita();
                    }
                };
                threadBotao.start();
                break;
        }
    }//GEN-LAST:event_jButton_cobrinhaKeyPressed

    private void jButton_cobrinha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cobrinha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cobrinha2ActionPerformed

    private void jButton_cobrinha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_cobrinha2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cobrinha2KeyPressed

    void paraCima() {
        do {
            try {
                this.jButton_cobrinha.setBounds(this.jButton_cobrinha.getX(),
                        this.jButton_cobrinha.getY() - 10,
                        this.jButton_cobrinha.getBounds().width, this.jButton_cobrinha.getBounds().width);
                pegou();
                //perseguir
                 if (!listaCauda.isEmpty()) {
                    for (int i = 0; i < listaCauda.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda.get(0)).setBounds(jButton_cobrinha.getX(), jButton_cobrinha.getY() + jButton_cobrinha.getHeight(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        } else {
                            ((JButton) listaCauda.get(i)).setBounds(((JButton) listaCauda.get(i - 1)).getX(), ((JButton) listaCauda.get(i - 1)).getY() + jButton_cobrinha.getHeight() , jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha.getY() <= 10) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraBaixo() {
        do {
            try {
                this.jButton_cobrinha.setBounds(this.jButton_cobrinha.getX(),
                        this.jButton_cobrinha.getY() + 10,
                        this.jButton_cobrinha.getBounds().width, this.jButton_cobrinha.getBounds().width);
                pegou();
                //perseguir
                if (!listaCauda.isEmpty()) {
                    for (int i = 0; i < listaCauda.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda.get(0)).setBounds(jButton_cobrinha.getX(), jButton_cobrinha.getY() - jButton_cobrinha.getHeight(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        } else {
                            ((JButton) listaCauda.get(i)).setBounds(((JButton) listaCauda.get(i - 1)).getX(), ((JButton) listaCauda.get(i - 1)).getY() - jButton_cobrinha.getHeight() , jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha.getY() >= jPanel_principal.getHeight() - jButton_cobrinha.getBounds().height) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraEsquerda() {
        do {
            try {
                this.jButton_cobrinha.setBounds(this.jButton_cobrinha.getX() - 10,
                        this.jButton_cobrinha.getY(),
                        this.jButton_cobrinha.getBounds().width, this.jButton_cobrinha.getBounds().width);
                pegou();
                //perseguir
                if (!listaCauda.isEmpty()) {
                    for (int i = 0; i < listaCauda.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda.get(0)).setBounds(jButton_cobrinha.getX() + jButton_cobrinha.getWidth(), jButton_cobrinha.getY(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        } else {
                            ((JButton) listaCauda.get(i)).setBounds(((JButton) listaCauda.get(i - 1)).getX() + jButton_cobrinha.getWidth(), jButton_cobrinha.getY(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        }
                    }
                }

                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha.getX() <= 10) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraDireita() {
        do {
            try {
                this.jButton_cobrinha.setBounds(this.jButton_cobrinha.getX() + 10,
                        this.jButton_cobrinha.getY(),
                        this.jButton_cobrinha.getBounds().width, this.jButton_cobrinha.getBounds().width);
                pegou();
                //perseguir
                if (!listaCauda.isEmpty()) {
                    for (int i = 0; i < listaCauda.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda.get(0)).setBounds(jButton_cobrinha.getX() - jButton_cobrinha.getWidth(), jButton_cobrinha.getY(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        } else {
                            ((JButton) listaCauda.get(i)).setBounds(((JButton) listaCauda.get(i - 1)).getX() - jButton_cobrinha.getWidth(), jButton_cobrinha.getY(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha.getX() >= jPanel_principal.getWidth() - jButton_cobrinha.getBounds().width) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }
    
        void paraCima1() {
        do {
            try {
                this.jButton_cobrinha2.setBounds(this.jButton_cobrinha2.getX(),
                        this.jButton_cobrinha2.getY() - 10,
                        this.jButton_cobrinha2.getBounds().width, this.jButton_cobrinha2.getBounds().width);
                pegou1();
                //perseguir
                 if (!listaCauda2.isEmpty()) {
                    for (int i = 0; i < listaCauda2.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda2.get(0)).setBounds(jButton_cobrinha2.getX(), jButton_cobrinha2.getY() + jButton_cobrinha2.getHeight(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        } else {
                            ((JButton) listaCauda2.get(i)).setBounds(((JButton) listaCauda2.get(i - 1)).getX(), ((JButton) listaCauda2.get(i - 1)).getY() + jButton_cobrinha2.getHeight() , jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha2.getY() <= 10) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.



        class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraBaixo1() {
        do {
            try {
                this.jButton_cobrinha2.setBounds(this.jButton_cobrinha2.getX(),
                        this.jButton_cobrinha2.getY() + 10,
                        this.jButton_cobrinha2.getBounds().width, this.jButton_cobrinha2.getBounds().width);
                pegou1();
                //perseguir
                if (!listaCauda2.isEmpty()) {
                    for (int i = 0; i < listaCauda2.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda2.get(0)).setBounds(jButton_cobrinha2.getX(), jButton_cobrinha2.getY() - jButton_cobrinha2.getHeight(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        } else {
                            ((JButton) listaCauda2.get(i)).setBounds(((JButton) listaCauda2.get(i - 1)).getX(), ((JButton) listaCauda2.get(i - 1)).getY() - jButton_cobrinha2.getHeight() , jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha2.getY() >= jPanel_principal.getHeight() - jButton_cobrinha2.getBounds().height) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraEsquerda1() {
        do {
            try {
                this.jButton_cobrinha2.setBounds(this.jButton_cobrinha2.getX() - 10,
                        this.jButton_cobrinha2.getY(),
                        this.jButton_cobrinha2.getBounds().width, this.jButton_cobrinha2.getBounds().width);
                pegou1();
                //perseguir
                if (!listaCauda2.isEmpty()) {
                    for (int i = 0; i < listaCauda2.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda2.get(0)).setBounds(jButton_cobrinha2.getX() + jButton_cobrinha2.getWidth(), jButton_cobrinha2.getY(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        } else {
                            ((JButton) listaCauda2.get(i)).setBounds(((JButton) listaCauda2.get(i - 1)).getX() + jButton_cobrinha2.getWidth(), jButton_cobrinha2.getY(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        }
                    }
                }

                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha2.getX() <= 10) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void paraDireita1() {
        do {
            try {
                this.jButton_cobrinha2.setBounds(this.jButton_cobrinha2.getX() + 10,
                        this.jButton_cobrinha2.getY(),
                        this.jButton_cobrinha2.getBounds().width, this.jButton_cobrinha2.getBounds().width);
                pegou1();
                
                //perseguir
                if (!listaCauda2.isEmpty()) {
                    for (int i = 0; i < listaCauda2.size(); i++) {
                        if (i == 0) {
                            ((JButton) listaCauda2.get(0)).setBounds(jButton_cobrinha2.getX() - jButton_cobrinha2.getWidth(), jButton_cobrinha2.getY(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        } else {
                            ((JButton) listaCauda2.get(i)).setBounds(((JButton) listaCauda2.get(i - 1)).getX() - jButton_cobrinha2.getWidth(), jButton_cobrinha2.getY(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
                        }
                    }
                }
                Thread.sleep(VELOCIDADE);

                if (this.jButton_cobrinha2.getX() >= jPanel_principal.getWidth() - jButton_cobrinha2.getBounds().width) {
                    break;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(JFrame_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (true);
    }

    void pegou() {
        
        if (jButton_cobrinha.getBounds().intersects(jButton_fruta.getBounds())) {
            
            VELOCIDADE = VELOCIDADE - 10;

            if (VELOCIDADE <= 30) {
                VELOCIDADE = 30;
            }

            jButton_fruta.setBounds(gerador.nextInt(jPanel_principal.getWidth() - jButton_cobrinha.getBounds().width),
                    gerador.nextInt(jPanel_principal.getHeight() - jButton_cobrinha.getBounds().height),
                    jButton_fruta.getBounds().width, jButton_fruta.getBounds().height);

            listaCauda.add(new JButton());
            
            contador++;
            placar1.setText(Integer.toString(contador));
            

            for (int i = 0; i < listaCauda.size(); i++) {
                jPanel_principal.add((JButton) listaCauda.get(listaCauda.size() - 1));
                ((JButton) listaCauda.get(listaCauda.size() - 1)).setBounds(jButton_cobrinha.getX(), jButton_cobrinha.getY(), jButton_cobrinha.getBounds().width, jButton_cobrinha.getBounds().height);
            }

        }
    }

        void pegou1() {
        if (jButton_cobrinha2.getBounds().intersects(jButton_fruta.getBounds())) {

            VELOCIDADE = VELOCIDADE - 10;
            if (VELOCIDADE <= 30) {
                VELOCIDADE = 30;
            }
            
            contador1++;
            placar2.setText(Integer.toString(contador1));

            jButton_fruta.setBounds(gerador.nextInt(jPanel_principal.getWidth() - jButton_cobrinha2.getBounds().width),
                    gerador.nextInt(jPanel_principal.getHeight() - jButton_cobrinha2.getBounds().height),
                    jButton_fruta.getBounds().width, jButton_fruta.getBounds().height);

            listaCauda2.add(new JButton());

            for (int i = 0; i < listaCauda2.size(); i++) {
                jPanel_principal.add((JButton) listaCauda2.get(listaCauda2.size() - 1));
                ((JButton) listaCauda2.get(listaCauda2.size() - 1)).setBounds(jButton_cobrinha2.getX(), jButton_cobrinha2.getY(), jButton_cobrinha2.getBounds().width, jButton_cobrinha2.getBounds().height);
            }

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Principal().setVisible(true);
                
            }
        });
    }

    Thread threadBotao;
    Thread threadBotao2;
    ArrayList listaCauda;
    ArrayList listaCauda2;
    int VELOCIDADE = 100;
    Random gerador = new Random();
    int contador = 0;
    int contador1 = 0;

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cobrinha;
    private javax.swing.JButton jButton_cobrinha2;
    private javax.swing.JButton jButton_fruta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JTextField placar1;
    private javax.swing.JTextField placar2;
    // End of variables declaration//GEN-END:variables
}
